### ISSUE TITLE
Provide Error Message for Low Bit Rate Audio

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CMU-CREATE-Lab/create-lab-visual-programmer#126]
```
Unable to play low quality .wav files. (The particular file causing the error 
below had a bit rate of 20 kbps ... java can handle down to 8-bit, 8kHz 
(64kbps?))

We should check for this and provide an error message.

***********************************************************
23:10:38,541 [pool-2-thread-2] DEBUG: AudioHelper.playClip(num bytes=8910)
23:10:38,543 [pool-2-thread-2] ERROR: UnsupportedAudioFileException while playin
g the sound
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input str
eam from input stream
        at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
        at edu.cmu.ri.createlab.audio.AudioHelper.playClip(AudioHelper.java:95)
        at edu.cmu.ri.createlab.hummingbird.BaseHummingbirdProxy.playClip(BaseHu
mmingbirdProxy.java:73)
        at edu.cmu.ri.createlab.hummingbird.services.AudioServiceImpl$2.run(Audi
oServiceImpl.java:92)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source
)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

```

Original issue reported on code.google.com by `jenncros...@gmail.com` on 4 Mar 2012 at 4:20
- Blocked on: #178

**Comment by ghost** [comment]
Dealt with as per #178 in BirdBrainDev
